import random   

numero_rand = random.randint(0,7)



nomes =(
"JHEDDER TRINDADE RAICHEL",
"MARCIO ANDRE CASTER MACHADO",
"MATEUS DA SILVA DORVIS",
"mateus fernandes",
"gabriel",
"lucas",
"daniel",
"alysson",
)


print(nomes[numero_rand])
#print(nomes[numero_rand2])














"""
nomes =(
"ALYSSON NARECIZO LORENO DE OLIVEIRA",
"BEATRIZ BUENO BIANCHI",
"BERNARDO KRUNITZKI BITTENCOURT",
"BRUNO OLIVEIRA DE SOUZA ",
"DANIEL HASHIZUME TANIOKA",
"ENZO GABRIJELCIC",
"FELIPE KLITZKE DE GODOI",
"FERNANDA FARIAS MORAES",
"GABRIEL GOMES DE CARVALHO",
"JHEDDER TRINDADE RAICHEL",
"LUCAS DO NASCIMENTO NUNES BAPTISTA",
"MARCIO ANDRE CASTER MACHADO",
"MATEUS DA SILVA DORVIS",
"MATHEUS FERNANDEZ FORGIARINI",
"OCTÁVIO AUGUSTO RAMIRES MACIEL",
"SARAH HASSEN CARDOSO ANTUNES",
)
"""